### ISSUE TITLE
Squishit ignores Bootstrap 3.3.0 stylesheet

### ISSUE THREAD

**Issue by peaeater** [jetheredge/SquishIt#304]
In Bootstrap 3.3.0 a workaround for Mobile Safari is introduced for temporal inputs, then an "IE 11 hack" reverses the hack. The latter produces styles like the following:

```css
_:-ms-fullscreen,
:root input[type="date"],
_:-ms-fullscreen,
:root input[type="time"],
_:-ms-fullscreen,
:root input[type="datetime-local"],
_:-ms-fullscreen,
:root input[type="month"] {
  line-height: 1.42857143;
}
```
Squishit ignores the Bootstrap source stylesheet when this syntax is present. In my case I am calling Squishit in an ASP.NET MVC Razor view:

```c#
@SquishIt.Framework.Bundle.Css()
.Add("bootstrap-3.3.0.css")
.MvcRender("styles.css")
```
Commenting out the offending styles makes Squishit include the Bootstrap source again. Bootstrap 3.3.1 does not include the "IE 11 hack" with the naughty syntax, so upgrading Bootstrap is another way to avoid this issue.
