### ISSUE TITLE
SquishIt Destroys Resolution of IE Filter

### ISSUE THREAD

**Issue by ericmann** [jetheredge/SquishIt#75]
It's common knowledge that IE doesn't support the CSS text-shadow property, so we're forced to use a proprietary "filter" property  to make the pages work properly.  For example, the following renders the same in Firefox, IE, Chrome, etc:

``` css
#element {
    text-shadow: 2px 2px #666;
    filter: shadow(Color=#666666, Direction=150, Strength=5);
}
```

However, if the color code is shortened (to #666 versus #6666), IE displays a very dark background shadow rather than what is intended.  SquishIt is automatically converting `filter: shadow(Color=#666666, Direction=150, Strength=5);` to `filter: shadow(Color=#666, Direction=150, Strength=5);` and destroying the display of the page!
